# url: localhost:4000
url: https://zhannas-adventures.netlify.app
# url: "https://planetzhanna.com" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/adventures/jekyll" # the subpath of your site, e.g. /blog
title: "Zhanna's Adventures" # the name of your site, e.g. ACME Corp.
timezone: America/New_York

collections:
  geocaches:
    output: false
  pages:
    output: true
  posts:
    permalink: /:year/:month/:day/:title

plugins:
  - jemoji # https://www.fabriziomusacchio.com/blog/2021-08-16-emojis_for_Jekyll/
  - jekyll-archives
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2 # The number of links after the current page
  title: ':title'  

autopages:  
  enabled: true
  collections:
    enabled: false    
  categories:
    layouts: 
      - 'category-archive.html'
    title: ':cat'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/categories/:cat'
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: 'raw'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts  

jekyll-archives:
  enabled:
  - year
  - month
  - day
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
