_select_data:
  mark_types:
    - Survey Mark
    - Reference Mark

collections_config:
  posts:
    schemas:
      default:
        path: schemas/post.md
  geocaches:
    schemas:
      default:
        path: schemas/geocache.md
    _inputs:
      zhanna_log:
        label: Zhanna's Log
        type: markdown
      rich_log:
        label: Rich's Log
        type: markdown
      layout:
        hidden: true